import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
import fs from 'fs/promises';
import path from 'path';

puppeteer.use(StealthPlugin());

export class CookieManager {
    private static cookiesCache: string | null = null;
    private static lastUpdate: number = 0;
    private static readonly CACHE_DURATION = 3600000; // 1 hour
    private static readonly COOKIES_FILE = './youtube-cookies.txt';

    static async getCookies(): Promise<string> {
        // Return cached cookies if still valid
        if (this.cookiesCache && Date.now() - this.lastUpdate < this.CACHE_DURATION) {
            console.log('[CookieManager] Using cached cookies');
            return this.cookiesCache;
        }

        // Try to load from file first
        try {
            const fileContent = await fs.readFile(this.COOKIES_FILE, 'utf-8');
            const fileAge = Date.now() - (await fs.stat(this.COOKIES_FILE)).mtimeMs;
            
            if (fileAge < this.CACHE_DURATION) {
                console.log('[CookieManager] Loaded cookies from file');
                this.cookiesCache = fileContent;
                this.lastUpdate = Date.now();
                return fileContent;
            }
        } catch (err) {
            console.log('[CookieManager] No valid cookies file found, fetching new ones...');
        }

        // Fetch new cookies using Puppeteer
        console.log('[CookieManager] Fetching fresh cookies from YouTube...');
        const cookies = await this.fetchFreshCookies();
        
        // Save to file
        await fs.writeFile(this.COOKIES_FILE, cookies, 'utf-8');
        
        this.cookiesCache = cookies;
        this.lastUpdate = Date.now();
        
        return cookies;
    }

    private static async fetchFreshCookies(): Promise<string> {
        console.log('[CookieManager] Launching headless Chrome...');
        
        const browser = await puppeteer.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--disable-software-rasterizer',
                '--disable-extensions'
            ]
        });

        try {
            const page = await browser.newPage();
            
            // Set realistic user agent
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
            
            // Visit YouTube
            console.log('[CookieManager] Visiting YouTube...');
            await page.goto('https://www.youtube.com', { 
                waitUntil: 'networkidle2',
                timeout: 30000 
            });
            
            // Wait for consent dialog and accept
            try {
                await page.waitForSelector('button[aria-label*="Accept"], button[aria-label*="Accetta"]', { timeout: 5000 });
                await page.click('button[aria-label*="Accept"], button[aria-label*="Accetta"]');
                console.log('[CookieManager] Accepted consent');
                await new Promise(resolve => setTimeout(resolve, 2000));
            } catch (err) {
                console.log('[CookieManager] No consent dialog found');
            }

            // Get cookies
            const cookies = await page.cookies();
            console.log('[CookieManager] Extracted', cookies.length, 'cookies');

            // Convert to Netscape format for yt-dlp
            const cookieLines = cookies.map(cookie => {
                return [
                    cookie.domain,
                    cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE',
                    cookie.path,
                    cookie.secure ? 'TRUE' : 'FALSE',
                    cookie.expires ? Math.floor(cookie.expires) : '0',
                    cookie.name,
                    cookie.value
                ].join('\t');
            });

            const cookieFileContent = [
                '# Netscape HTTP Cookie File',
                '# Generated by puppeteer-cookie-extractor',
                '',
                ...cookieLines
            ].join('\n');

            return cookieFileContent;
        } finally {
            await browser.close();
            console.log('[CookieManager] Browser closed');
        }
    }

    static clearCache() {
        this.cookiesCache = null;
        this.lastUpdate = 0;
    }
}